export const expenseManagement = {
  "data": [],
  "general": {
    "businessSupport": null,
    "empOutcome": null,
    "endRemain": null,
    "fixedDifferent": null,
    "openingRemaining": null,
    "remainDiff": null,
    "totalIncome": null,
    "totalSupportOutcome": null,
  },
  "isValue": null,
}

export const AvgSalary = {
  "data": [],
  "general": {
    "avgIncome": '',
    "contractSalary": '',
    "empAmount": '',
    "icon": '',
    "incentiveSalary": '',
    "avgVasAffiliate":'',
    "permanentSalary": '',
    "shopCode": '',
    "shopName": '',
    "spenSupport": '',
  },
  "notification": '',
}

export const User = {
  "accessToken": null,
  "expiredAt": null,
  "id": null,
  "refreshExpiredAt": null,
  "refreshToken": null,
  "userId": {
    "avatar": null,
    "displayName": null,
    "gdvId": null,
    "id": null,
    "isLDap": null,
    "password": null,
    "phoneNumber": null,
    "shopId": {
      "id": null,
      "parentShopId": {
        "id": null,
        "parentShopId": {
          "id": null,
          "parentShopId": null,
          "shopCode": null,
          "shopLevel": null,
          "shopName": null,
          "shopTypeId": null,
        },
        "shopCode": null,
        "shopLevel": null,
        "shopName": null,
        "shopTypeId": null
      },
      "shopCode": null,
      "shopLevel": null,
      "shopName": null,
      "shopTypeId": null,
    },
    "status": null,
    "userGroupId": {
      "code": null,
      "description": null,
      "id": null,
    },
    "userName": null,
  },
}

export const ViolateWarning = {
  "transFc": {
    "emp": null,
    "top": null
  },
  "isValue": true,
  "denyTwoC": {
    "emp": null,
    "top": null
  },
  "wrongNumber": null,
  "noRecharge": null,
  "overThree": null,
  "resident": {
    "emp": null,
    "top": null
  }
}

export const Violate = [{
  "notification":null,
  "fast":null,
  "overThreeTime":null,
  "fcard":null,
}]

export const DetailOutcome = {
      "notification": null,
      "beginMonth": null,
      "endMonth": null,
      "empAmount": null,
      "outcomeBusiness": null,
      "outcomeEmp": null,
      "outcomeBusinessMonth": null,
      "outcomeEmpMonth": null,
      "outcomeDiff": null,
      "permanentBusiness": null,
      "permanentEmp": null,
      "permanentBusinessMonth": null,
      "permanentEmpMonth": null,
      "permanentDiff": null,
      "contractBusiness": null,
      "contractEmp": null,
      "contractBusinessMonth": null,
      "contractEmpMonth": null,
      "contractDiff":null,
      "prepaidSubBusiness":null,
      "prepaidSubEmp":null,
      "prepaidSubBusinessMonth":null,
      "prepaidSubEmpMonth":null,
      "prepaidSubDiff":null,
      "commissionBusiness":null,
      "commissionEmp":null,
      "commissionBusinessMonth":null,
      "commissionEmpMonth":null,
      "commissionDiff":null,
      "ppgldBusiness":null,
      "ppgldEmp":null,
      "ppgldBusinessMonth":null,
      "ppgldEmpMonth":null,
      "ppgldDiff":null,
      "maintainBusiness":null,
      "maintainEmp":null,
      "maintainBusinessMonth":null,
      "maintainEmpMonth":null,
      "maintainDiff":null,
      "postpaidSubBusiness":null,
      "postpaidSubEmp":null,
      "postpaidSubBusinessMonth":null,
      "postpaidSubEmpMonth":null,
      "postpaidSubDiff":null,
      "ezBusiness":null,
      "ezEmp":null,
      "ezBusinessMonth":null,
      "ezEmpMonth":null,
      "ezDiff":null,
      "vasBusiness":null,
      "vasEmp":null,
      "vasBusinessMonth":null,
      "vasEmpMonth":null,
      "vasDiff":null,
      "cardBusiness":null,
      "cardEmp":null,
      "cardBusinessMonth":null,
      "cardEmpMonth":null,
      "cardDiff":null,
      "servicesBusiness":null,
      "servicesEmp":null,
      "servicesBusinessMonth":null,
      "servicesEmpMonth":null,
      "servicesDiff":null,
      "chargeableBusiness":null,
      "chargeableEmp":null,
      "chargeableBusinessMonth":null,
      "chargeableEmpMonth":null,
      "chargeableDiff":null,
      "machineBusiness":null,
      "machineEmp":null,
      "machineBusinessMonth":null,
      "machineEmpMonth":null,
      "machineDiff":null,
      "totalOutcomeSupportBusiness": null,
      "totalOutcomeSupportEmp": null,
      "totalOutcomeSupportBusinessMonth": null,
      "totalOutcomeSupportDiff":null,
      "outcomeBusinessMaster":null,
      "outcomeEmpMaster":null,
      "outcomeBusinessMonthMaster": null,
      "outcomeBusinessEmpMaster": null,
      "outcomeDiffMaster":null,
      "otherOutcomeBusinessMaster": null,
      "otherOutcomeEmpMaster": null,
      "otherOutcomeBusinessMonthMaster": null,
      "otherOutcomeBusinessEmpMaster": null,
      "otherOutcomeBusinessDiff": null,
      "otherTotalOutcomeEmp": null,
      "otherTotalOutcomeBusinessMonth": null,
      "otherTotalOutcomeBusinessEmp": null,
      "incentiveOutcomeEmp": null,
      "incentiveOutcomeBusinessMonth": null,
      "incentiveOutcomeBusinessEmp": null,
      "vasAffiEmp":null,
      "vasAffiBusinessMonth":null,
      "vasAffiBusinessEmp":null,
      "otherEmp":null,
      "otherAvgMonth":null,
      "otherAvgMonthEmp":null,
      "moneyFollow":null,
      "avgMonthFollow":null,
      "avgMonthEmpFollow":null,
      "moneyArrears":null,
      "avgMonthArrears":null,
      "avgMonthEmpArrears":null,
      "moneyPunishment":null,
      "avgMonthPunishment":null,
      "avgMonthEmpPunishment":null
}

export const AccumulatedCost = { 
  'notification': null, 
  'outcome': null, 
  'outcomeBusiness': null, 
  'outcomeEmp': null, 
  'outcomeDiff': null, 
  'outcomeAvg': null, 
  'permanentBusiness': null, 
  'permanentEmp': null, 
  'permanentDiff': null, 
  'permanentAvg': null, 
  'contractBusiness': null, 
  'contractEmp': null, 
  'contractDiff': null, 
  'contractAvg': null, 
  'othersBusiness': null, 
  'othersEmp': null, 
  'othersDiff': null, 
  'othersAvg': null, 
  'remain': null, 
  'expected': null, 
  'diffMoney': null, 
  'totalSupport':null, 
 
  'totalOutcome': null, 
  'outcomeMaster': null, 
  'avgMaster': null, 
  'otherOutcomeMaster': null, 
  'otherAvgMaster': null, 
  'incomeTotalOutcome': null, 
  'incomeAvgOutcome': null, 
  'supportRemain': null, 
  'expectedSupport': null 
 }